### ISSUE TITLE
Error when using fusioncatcher-build function (faulted at step 23 Gencode for both mouse & human))

### ISSUE THREAD

**Issue by YIN72** [ndaniel/fusioncatcher#109]
I am completely new to linux and bioinformatics. And do not know if the entire download has been completed and whether this would affect the performance of the program.

I am using the "1.00 version of FusionCatcher" and download the database using this code:

`sudo fusioncatcher-build -g mus_musculus -o /opt/fusioncatcher/data/mouse`
`sudo fusioncatcher-build -g homo_sapiens -o /opt/fusioncatcher/data/human`

And the error message was: (and I am not sure it is normal that in multiple previous step (for example step 22 as shown below, there were only 0.01 MB data downloaded) 
```
...
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 15 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 21   Time: 10:11   Date: 2019-02-14 (elapsed time: 0d:0h:13m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/home/yin'
get_refseq.py \
--organism homo_sapiens \
--server hgdownload.cse.ucsc.edu \
--output /opt/fusioncatcher/data/human/
--------------------------------------------------------------------------------
+-->EXECUTING...
Downloading the SQL files of organism 'homo_sapiens' from UCSC!
230 User anonymous logged in.
Downloading: hgdownload.cse.ucsc.edugoldenPath/hg38/database/refFlat.txt.gz
Downloading: hgdownload.cse.ucsc.edugoldenPath/hg38/database/refFlat.sql
Decompressing files ...
Parsing the MySQL files...
46227 genes found in 'refFlat.txt'!
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 8 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 22   Time: 10:11   Date: 2019-02-14 (elapsed time: 0d:0h:13m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/home/yin'
get_refseq_ensembl.py \
--organism homo_sapiens \
--server www.ensembl.org \
--output /opt/fusioncatcher/data/human/
--------------------------------------------------------------------------------
+-->EXECUTING...
Starting query 1 / 2 ...
Downloaded:      0.01 MB
Downloaded:      0.01 MB

Starting query 2 / 2 ...
Downloaded:      0.01 MB
Downloaded:      0.01 MB

End.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 46 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 23   Time: 10:12   Date: 2019-02-14 (elapsed time: 0d:0h:14m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/home/yin'
get_gencode.py \
--organism homo_sapiens \
--output /opt/fusioncatcher/data/human/
--------------------------------------------------------------------------------
+-->EXECUTING...
Downloading the GTF file of organism 'homo_sapiens' from Gencode!
230 Anonymous access granted, restrictions apply
FTP Error = 550 pub/gencode/Gencode_human/: No such file or directory


ERROR: Workflow execution failed at step 23 while executing:
----------------
   get_gencode.py \
   --organism homo_sapiens \
   --output /opt/fusioncatcher/data/human/
----------------


Executing second time the same step/command in order to capture error messages (i.e. STDERR)...

-------------------------------------------
Downloading the GTF file of organism 'homo_sapiens' from Gencode!
230 Anonymous access granted, restrictions apply
FTP Error = 550 pub/gencode/Gencode_human/: No such file or directory
################################################################################
################################################################################
TOTAL RUNNING TIME: 0 day(s), 0 hour(s), 13 minute(s), and 41 second(s) 
################################################################################
################################################################################
```
Many thanks for your help!!

**Comment by YIN72** [comment]
When I tried to test for the installation using:
`/opt/fusioncatcher/test/test.sh`

It appears that the "organism.txt" was not found in the "/data/current folder": 
```
Checking Python version...
  * Compatible Python version found!
Checking size of installed RAM memory ...
  * 32031 MB of RAM memory found!
Traceback (most recent call last):
  File "/opt/fusioncatcher/test/../bin/fusioncatcher.py", line 1936, in <module>
    organism = file(datadir("organism.txt"),"r").readline().rstrip('\r\n').lower()
IOError: [Errno 2] No such file or directory: '/opt/fusioncatcher/data/current/organism.txt'
sort: cannot read: test_fusioncatcher/summary_candidate_fusions.txt: No such file or directory



   WARNING: Test is NOT ok! There is something wrong with FusionCatcher installation!   

```

**Comment by ndaniel** [comment]
Installing FusionCatcher using the official installation method should work and fix your issues.

This is the recommended and official way to install FusionCatcher:
```
wget http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py && python bootstrap.py -t --download
``

**Comment by YIN72** [comment]
@ndaniel thanks for your help

but I have just encountered error when using the official installation command: (do I need to remove my previous installation of FusionCatcher and other dependence before re-installing?)

```
$wget http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py && python bootstrap.py -t --download
--2019-02-14 15:20:24--  http://sf.net/projects/fusioncatcher/files/bootstrap.py
Resolving sf.net (sf.net)... 216.105.38.13
Connecting to sf.net (sf.net)|216.105.38.13|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sf.net/projects/fusioncatcher/files/bootstrap.py [following]
--2019-02-14 15:20:24--  https://sf.net/projects/fusioncatcher/files/bootstrap.py
Connecting to sf.net (sf.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sourceforge.net/projects/fusioncatcher/files/bootstrap.py [following]
--2019-02-14 15:20:25--  https://sourceforge.net/projects/fusioncatcher/files/bootstrap.py
Resolving sourceforge.net (sourceforge.net)... 216.105.38.13
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://sourceforge.net/projects/fusioncatcher/files/bootstrap.py/download [following]
--2019-02-14 15:20:26--  https://sourceforge.net/projects/fusioncatcher/files/bootstrap.py/download
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://downloads.sourceforge.net/project/fusioncatcher/bootstrap.py?r=&ts=1550128826&use_mirror=jaist [following]
--2019-02-14 15:20:27--  https://downloads.sourceforge.net/project/fusioncatcher/bootstrap.py?r=&ts=1550128826&use_mirror=jaist
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://jaist.dl.sourceforge.net/project/fusioncatcher/bootstrap.py [following]
--2019-02-14 15:20:27--  https://jaist.dl.sourceforge.net/project/fusioncatcher/bootstrap.py
Resolving jaist.dl.sourceforge.net (jaist.dl.sourceforge.net)... 2001:df0:2ed:feed::feed, 150.65.7.130
Connecting to jaist.dl.sourceforge.net (jaist.dl.sourceforge.net)|2001:df0:2ed:feed::feed|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 96495 (94K) [application/octet-stream]
Saving to: ‘bootstrap.py’

bootstrap.py                   100%[==================================================>]  94.23K   379KB/s    in 0.2s    

2019-02-14 15:20:28 (379 KB/s) - ‘bootstrap.py’ saved [96495/96495]

  File "bootstrap.py", line 315
    print "Checking latest version of Ensembl database that is available..."
                                                                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Checking latest version of Ensembl database that is available...")?
```

**Comment by ndaniel** [comment]
This error shows up because python 3 is used instead of python 2.

Try this:
```
wget http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py && python2 bootstrap.py -t --download
```

**Comment by YIN72** [comment]
it works! thanks @ndaniel

**Comment by YIN72** [comment]
Hi @ndaniel,
I am still struggling with the build downloading issue.
I tried to use the following code to download the build for mouse reference sequences:
`python2 '/home/yin/fusioncatcher/bin/fusioncatcher-build.py' -g mus_musculus -o '/home/yin/fusioncatcher/data/mouse' `
and it seemed that the code kept downloading only 0.01 MB data from step 11 through step 22:
```
End.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 6 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 11   Time: 12:28   Date: 2019-03-07 (elapsed time: 0d:0h:1m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/home/yin'
get_genes_descriptions.py \
--organism mus_musculus \
--server www.ensembl.org \
--output /home/yin/fusioncatcher/data/mouse/
--------------------------------------------------------------------------------
+-->EXECUTING...
Starting...
Downloaded:      0.01 MB
Downloaded:      0.01 MB

End.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 12   Time: 12:28   Date: 2019-03-07 (elapsed time: 0d:0h:2m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/home/yin'
get_exons_positions.py \
--organism mus_musculus \
--server www.ensembl.org \
--threshold_length 150 \
--output /home/yin/fusioncatcher/data/mouse/
--------------------------------------------------------------------------------
+-->EXECUTING...
Starting...
Get lists of chromosomes...
Downloaded:      0.01 MB
FINISHED downloading:      0.01 MB

End.
....
////////////////////////////////////////////////////////////////////////////////
  Running: step = 22   Time: 12:29   Date: 2019-03-07 (elapsed time: 0d:0h:2m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/home/yin'
get_gencode.py \
--organism mus_musculus \
--output /home/yin/fusioncatcher/data/mouse/
--------------------------------------------------------------------------------
+-->EXECUTING...
Downloading the GTF file of organism 'mus_musculus' from Gencode!
230 Anonymous access granted, restrictions apply
FTP Error = 550 pub/gencode/Gencode_mouse/: No such file or directory


ERROR: Workflow execution failed at step 22 while executing:
----------------
   get_gencode.py \
   --organism mus_musculus \
   --output /home/yin/fusioncatcher/data/mouse/
----------------


Executing second time the same step/command in order to capture error messages (i.e. STDERR)...

-------------------------------------------
Downloading the GTF file of organism 'mus_musculus' from Gencode!
230 Anonymous access granted, restrictions apply
FTP Error = 550 pub/gencode/Gencode_mouse/: No such file or directory
################################################################################
################################################################################
TOTAL RUNNING TIME: 0 day(s), 0 hour(s), 1 minute(s), and 40 second(s) 
################################################################################
################################################################################
```
When I tried to run for the fusioncatcher program using the script:
`python2 '/home/yin/fusioncatcher/bin/fusioncatcher.py' -d '/home/yin/fusioncatcher/data/mouse' -i '/media/yin/0CAB7E4E193305EF/_rawdata' -o '/media/yin/0CAB7E4E193305EF/Analyzed`
It showed:
```
Checking Python version...
  * Compatible Python version found!
Checking size of installed RAM memory ...
  * 32031 MB of RAM memory found!



ERROR: The build data not found in '/home/yin/fusioncatcher/data/mouse/'!

```

**Comment by ilykos** [comment]
> --------------------------------------------------------------------------------
> +-->EXECUTING...
> Downloading the GTF file of organism 'mus_musculus' from Gencode!
> 230 Anonymous access granted, restrictions apply
> FTP Error = 550 pub/gencode/Gencode_mouse/: No such file or directory
> 
> 
> ERROR: Workflow execution failed at step 22 while executing:
> ----------------
>    get_gencode.py \
>    --organism mus_musculus \
>    --output /home/yin/fusioncatcher/data/mouse/
> ----------------
> 
> 
> Executing second time the same step/command in order to capture error messages (i.e. STDERR)...
> 
> -------------------------------------------
> Downloading the GTF file of organism 'mus_musculus' from Gencode!
> 230 Anonymous access granted, restrictions apply
> FTP Error = 550 pub/gencode/Gencode_mouse/: No such file or directory

The database link in **get_gencode.py** is outdated.

@ndaniel Since gencode was moved to ftp.ebi.ac.uk. Please introduce following changes in **get_gencode.py**:

```
    parser.add_option("--server",
                      action="store",
                      type="string",
                      dest="server",
                      default = "ftp.ebi.ac.uk", '%default'.""")
```



```
   if org:

        url = 'pub/databases/gencode/%s/' % (org,)0
```

This will fix the fusioncatcher-build.py
