### ISSUE TITLE
Error with test dataset

### ISSUE THREAD

**Issue by mdeloger** [ndaniel/fusioncatcher#147]
Hi Daniel,

I used bioconda channel to install fusioncatcher (the fusioncatcher --version give me 1.20) but here what I have as error when I try to test it on your provided test dataset : 
```
-------------------------------------------
java -Djava.library.path=/bioinfo/local/build/Centos/envs_conda/fusioncatcher_1.20/opt/bbmap-38.44-0/jni/ -ea -Xmx7504m -Xms7504m -cp /bioinfo/local/build/Centos/envs_conda/fusioncatcher_1.20/opt/bbmap-38.44-0/current/ jgi.BBDuk forcetrimmod=5 in=/data/users/mdeloger/Documents/KDI_projects/Softwares_Benchmark/Fusioncatcher/FusionCatcher_Out/test/orig__.fq out=/data/users/mdeloger/Documents/KDI_projects/Softwares_Benchmark/Fusioncatcher/FusionCatcher_Out/test/orig__x.fq
Executing jgi.BBDuk [forcetrimmod=5, in=/data/users/mdeloger/Documents/KDI_projects/Softwares_Benchmark/Fusioncatcher/FusionCatcher_Out/test/orig__.fq, out=/data/users/mdeloger/Documents/KDI_projects/Softwares_Benchmark/Fusioncatcher/FusionCatcher_Out/test/orig__x.fq]
Version 38.44

0.050 seconds.
Initial:
Memory: max=7868m, total=7868m, free=7848m, used=20m

Input is being processed as paired
Started output streams:	0.139 seconds.
Warning! Changed from ASCII-33 to ASCII-64 on input A: 65 -> 34
Up to 11009 prior reads may have been generated with incorrect qualities.
If this is a problem you may wish to re-run with the flag 'qin=33' or 'qin=64'.

The ASCII quality encoding offset (64) is not set correctly, or the reads are corrupt; quality value below -5.
Please re-run with the flag 'qin=33', 'ignorebadquality', or '-da'.
Problematic read number 11201:

@11202/1
GGCTGCCAGACACTTTTCCTGGAGACACCATTTGGTTCTCAGAACTTCCTGGGCTCTGGGAAGAGCTTGAGCAGTCCAGGTCAGCCAGGGCACCTGGGCCA
+
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@AB@@@@DDC@@@BAB

Offset=64
java.lang.Exception: Aborting.
	at shared.KillSwitch.kill(KillSwitch.java:108)
	at stream.FASTQ.quadToRead_slow(FASTQ.java:754)
	at stream.FASTQ.toReadList(FASTQ.java:625)
	at stream.FastqReadInputStream.fillBuffer(FastqReadInputStream.java:107)
	at stream.FastqReadInputStream.nextList(FastqReadInputStream.java:93)
	at stream.ConcurrentGenericReadInputStream$ReadThread.readLists(ConcurrentGenericReadInputStream.java:680)
	at stream.ConcurrentGenericReadInputStream$ReadThread.run(ConcurrentGenericReadInputStream.java:656)


################################################################################
################################################################################
TOTAL RUNNING TIME: 0 day(s), 0 hour(s), 0 minute(s), and 10 second(s) 
################################################################################
################################################################################

```

Do you have an idea of the possible issue ?

Thank you in advance

**Comment by ndaniel** [comment]
This is related to issue https://github.com/ndaniel/fusioncatcher/issues/144

**Comment by ndaniel** [comment]
@mdeloger , if you still have this issue, please re-open it! The bioconda installation of FusionCatcher has been fixed.
