### ISSUE TITLE
Cannot allocate memory & threads

### ISSUE THREAD

**Issue by ndaniel** [ndaniel/fusioncatcher#15]
In some cases, FusionCatcher v0.99.5a failed to run (when using 4 threads while running *find_homolog_genes.py*) with the following error message:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 302, in _handle_workers
    pool._maintain_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 206, in _maintain_pool
    self._repopulate_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 199, in _repopulate_pool
    w.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 120, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```
It looks like it might be related to this issue:
http://stackoverflow.com/questions/26717120/python-cannot-allocate-memory-using-multiprocessing-pool

The workaround is to run FusionCatcher using only one thread (i.e. -p 1) until this fixed.

**Comment by ndaniel** [comment]
Fixed in v0.99.6a.
