### ISSUE TITLE
BBMap causes test.sh error

### ISSUE THREAD

**Issue by tom-sober** [ndaniel/fusioncatcher#156]
Hi,

I followed the instruction and installed fusioncatcher by this command:
wget http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py && python bootstrap.py -t --download

After installation, I ran ./test/test.sh which ends with an error at the BBMap check step:
![screen](https://user-images.githubusercontent.com/61877486/76094715-6ba0ec00-6006-11ea-8712-5a0ab984ed4a.png)

BBMap version 38.44 seems to be successfully installed and I wonder why the test.sh fails... Am I missing something?

Thanks,

Tom

**Comment by ndaniel** [comment]
Hi @tom-sober 

could you post the `/yshare2/home/isobe/analysis/fusioncatcher/test_fusioncatcher/info.txt` file that was created during the test?

Cheers,
Daniel

**Comment by tom-sober** [comment]
Hi Daniel,

Thanks for your reply! Please see the attached info.txt file.
[info.txt](https://github.com/ndaniel/fusioncatcher/files/4301713/info.txt)

Tom

**Comment by tom-sober** [comment]
I copy and paste the output in the info.txt.
Thanks,

Tom

```
================================================
Software version: fusioncatcher.py 1.20
================================================


===================================
GENOME INFORMATION:
===================================
fusioncatcher-build.py 1.20
Ensembl database version: 98
Organism: Homo sapiens
Genome version: GRCh38
NCBI Viral Genomes version: 2019-09-12
UCSC database version (hg38): 2018-11-18
RefSeq NCBI database version (downloaded thru UCSC database; hg38): 2019-07-28
Gencode database version: 32
Non-cancer tissues and cells (Babiceanu et al. Nucl. Acids Res. 2016) database version: 2019-10-07
Cancer Gene List database version: 2019-10-07
Oncogenes database version: 2019-10-07
TumorFusions (Hu et al. Nucleic Acids Research) database version: Nov. 2017
TCGA Fusions Dataset (Qingsong G., Cell Reports, 2018) version: April 2018
Cell lines (Klijn et al. Nature Biotechnology 2014) database version: 2019-10-07
Prostate Tumor Patients (Robison et al. Cell 2015) database version: 2019-10-07
Pancreatic Tumor Patients (Bailey et al. Nature 2016) database version: 2019-10-07
ChimerDB database version: 2.0
ChimerDB database version: 3.0
TICdb database version: 2019-10-07
ConjoinG database version: 2019-10-07
CGP database version: 2019-10-07
CACG database version: 2019-10-07
DGD database version: 2019-10-07
GTEx database version (thru FusionAnnotator): 2019-10-08
OncoKB (Chakravarty et al., JCO PO 2017): 2019-10-08
Mitelman database version: 2019-10-08

===================================
Genome FASTA files:
===================================
ftp.ensembl.org//pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa




Linux:
------
\S
Kernel \r on an \m


Python:
------
Python version: 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:56:06) 
[GCC 7.3.0]
Python executable: /home/isobe/.pyenv/versions/anaconda3-5.2.0/envs/py27/bin/python

BioPython:
------
1.74

===========
TOOLS:
===========

SORT:
------
sort (GNU coreutils) 8.22

BOWTIE:
------
/yshare2/home/isobe/analysis/fusioncatcher/tools/bowtie-1.2.3-linux-x86_64/bowtie-align-s version 1.2.3
64-bit

BBMAP:
------
java -ea -Xmx68402m -cp /yshare2/home/isobe/analysis/fusioncatcher/tools/bbmap/current/ align2.BBMap build=1 overwrite=true fastareadlen=500 --version
Picked up JAVA_TOOL_OPTIONS: -XX:+UseSerialGC -Xmx64m -Xms32m
BBMap version 38.44
For help, please run the shellscript with no parameters, or look in /docs/.
```

**Comment by ndaniel** [comment]
Hi @tom-sober 

it looks like a bug in FusionCatcher v1.20.

Please, edit manually the file `fusioncatcher.py` and change line number 2325 from:
```
    os.system(_BP_+"bbmap.sh --version 2>&1 |head -2 |tail -1 > '%s'" % (outdir('bbmap_version.txt'),))
```
into
```
    os.system(_BP_+"bbmap.sh --version 2>&1 |head -3 |tail -1 > '%s'" % (outdir('bbmap_version.txt'),))
```

(where `head -2` becomes `head -3`).

Hopefully, this fixes your case. In the next release of FusionCatcher will be a more permanent fix available.

**Comment by tom-sober** [comment]
Hi Daniel,

That correction fixed the BBMap version error, but now I have another error...
I'm posting the last part of `test_fusioncatcher/fusioncatcher.log` file. Could you tell what the problem is?

Thanks,
Tom

```
////////////////////////////////////////////////////////////////////////////////
  Running: step = 91   Time: 20:10   Date: 2020-03-10 (elapsed time: 0d:0h:1m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/yshare2/home/isobe/analysis/fusioncatcher'
sra2illumina.py \
--input_1 /yshare2/home/isobe/analysis/fusioncatcher/test_fusioncatcher/init-clear-noadapt-0_reads_1.fq \
--input_2 /yshare2/home/isobe/analysis/fusioncatcher/test_fusioncatcher/init-clear-noadapt-1_reads_2.fq \
--output_1 /yshare2/home/isobe/analysis/fusioncatcher/test_fusioncatcher/init-sra-clear-noadapt-0_reads_1.fq \
--output_2 /yshare2/home/isobe/analysis/fusioncatcher/test_fusioncatcher/init-sra-clear-noadapt-1_reads_2.fq \
--link hard \
--tmp_dir /yshare2/home/isobe/analysis/fusioncatcher/test_fusioncatcher/tmp/
--------------------------------------------------------------------------------
+-->EXECUTING...


ERROR: Workflow execution failed at step 91 while executing:
----------------
   sra2illumina.py \
   --input_1 /yshare2/home/isobe/analysis/fusioncatcher/test_fusioncatcher/init-clear-noadapt-0_reads_1.fq \
   --input_2 /yshare2/home/isobe/analysis/fusioncatcher/test_fusioncatcher/init-clear-noadapt-1_reads_2.fq \
   --output_1 /yshare2/home/isobe/analysis/fusioncatcher/test_fusioncatcher/init-sra-clear-noadapt-0_reads_1.fq \
   --output_2 /yshare2/home/isobe/analysis/fusioncatcher/test_fusioncatcher/init-sra-clear-noadapt-1_reads_2.fq \
   --link hard \
   --tmp_dir /yshare2/home/isobe/analysis/fusioncatcher/test_fusioncatcher/tmp/
----------------
  * Size '/yshare2/home/isobe/analysis/fusioncatcher/test_fusioncatcher/init-clear-noadapt-0_reads_1.fq' = 2647206 bytes
  * Size '/yshare2/home/isobe/analysis/fusioncatcher/test_fusioncatcher/init-clear-noadapt-1_reads_2.fq' = 2647206 bytes
  * Size '/yshare2/home/isobe/analysis/fusioncatcher/test_fusioncatcher/init-sra-clear-noadapt-0_reads_1.fq' = 0 bytes
  * Size '/yshare2/home/isobe/analysis/fusioncatcher/test_fusioncatcher/init-sra-clear-noadapt-1_reads_2.fq' = 0 bytes


Executing second time the same step/command in order to capture error messages (i.e. STDERR)...

-------------------------------------------
/yshare2/home/isobe/analysis/fusioncatcher/tools/biopython/Bio/__init__.py:128: BiopythonWarning: You may be importing Biopython from inside the source tree. This is bad practice and might lead to downstream issues. In particular, you might encounter ImportErrors due to missing compiled C extensions. We recommend that you try running your code from outside the source tree. If you are outside the source tree then you have a setup.py file in an unexpected directory: /yshare2/home/isobe/analysis/fusioncatcher/tools/biopython.
  format(_parent_dir), BiopythonWarning)
Traceback (most recent call last):
  File "/yshare2/home/isobe/analysis/fusioncatcher/bin/sra2illumina.py", line 48, in <module>
    import phred
  File "/yshare2/home/isobe/analysis/fusioncatcher/bin/phred.py", line 58, in <module>
    import Bio.SeqIO
  File "/yshare2/home/isobe/analysis/fusioncatcher/tools/biopython/Bio/SeqIO/__init__.py", line 387, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "/yshare2/home/isobe/analysis/fusioncatcher/tools/biopython/Bio/Align/__init__.py", line 22, in <module>
    from Bio.Align import _aligners
ImportError: cannot import name _aligners


################################################################################
################################################################################
TOTAL RUNNING TIME: 0 day(s), 0 hour(s), 0 minute(s), and 10 second(s) 
################################################################################
################################################################################
 ```

**Comment by ndaniel** [comment]
Hello @tom-sober 

great that that fix helped!

Regarding the new error, it looks to me that the issue is related with Python (and BioPython?) not being installed correctly.

From your log it looks like Python is installed via conda:
```
Python version: 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:56:06) 
[GCC 7.3.0]
Python executable: /home/isobe/.pyenv/versions/anaconda3-5.2.0/envs/py27/bin/python
```
Probably it would help, to install Python without using Conda.

**Comment by tom-sober** [comment]
Hi Daniel,

The error was fixed after the following steps:
1) removed (uninstalled) the `fusioncatcher` root directory
2) removed `py27` the anaconda virtual environment for using python 2.7
3) re-created a new anaconda virtual environment for python 2.7
4) `conda install`ed Numpy and Biopython
5) re-installed `fusioncatcher` using the `bootstrap.py`
6) corrected the line number 2325 of `fusioncatcher.py` as discussed above.

At first I installed Biopython not by `conda install` but locally under the `fusioncatcher` root directory by `bootstrap.py`, which seems to have caused some conflicts?

Anyway FusionCatcher could successfully be installed under a conda virtual environment.
Thank you for your help!

Tom

**Comment by ndaniel** [comment]
Great!

In general FusionCatcher does not work well when **some** software tools (but not all of them) are installed using Conda/anacoda. FusionCatcher works well if all all the tools are installed using conda or FusionCatcher is installed using Conda.
