### ISSUE TITLE
Error message said bad quality while running bbduk

### ISSUE THREAD

**Issue by yazuo0204** [ndaniel/fusioncatcher#167]
Hi, 
I've used a filtered reads for fusioncatcher which filtered out quality less than 7 in fastq, but it still report that some quality lowered than 5. 
I download the fusioncatcher through conda,  version is 1.20. Actually the manual downloaded one would report same error message to me.
Here is the error info: 

```
fusioncatcher.py -d /home/user/zuoya/Test/03.Gene_Fusion/01.fusioncatcher/human/data/human_v98/ -i /home/user/zuoya/Test/03.Gene_Fusion/01.fusioncatcher/ --single-end -o output

Input is being processed as paired
Started output streams: 0.013 seconds.
Warning! Changed from ASCII-33 to ASCII-64 on input 8: 56 -> 25
Up to 420 prior reads may have been generated with incorrect qualities.
If this is a problem you may wish to re-run with the flag 'qin=33' or 'qin=64'.

The ASCII quality encoding offset (64) is not set correctly, or the reads are corrupt; quality value below -5.
Please re-run with the flag 'qin=33', 'ignorebadquality', or '-da'.
Problematic read number 420:

@fa7c71b9-8840-4513-a44d-b1075e856b1f/1
CGCAGGGUUAGUGGCGGCUGGAGGCGAUCAUGGUUCGCCCGACAGCUACCGCUUCACCUUUUGCCUCCCGCUAUGCCAGCCCGGAAGAUGUGCUCGUGUUUAGCGACAGGUAUAAAUUCCGGACAUGGCGGCAGCUGUGGCUGUGGCUGGCGGAGGCCGAGCAGACACUGGGUUUGCCUAUCACAGAUGACAAUCCAGGAGAUGAAUCAAACCUGGAGAACAUCGACUUCAAGAUGAUGGCAGCUGAGGAAGAGAAACGUCUUACGACAUGAUGUGAUGGCUACGUGCACACAUUUAGCCUUGCUGUCCAAAAGCUGCAGGCAUUAUUCACCUUGGUGCAUUUCUUGUAUGUUGACAAUACCGACUUGAUUAUUCUUAGAAACGUGAGGCCUGCUUUUGCCAAAGCUCGCCAGAGUGAUCUCUCGGCUCAAUGACUCUGCACUGGGAACGGGCCAGUCUACCCACAUUAGGUUUCUCUCCAUCUCCAGCCUGCACAGCUGACCACAGUUGGGAAACGUUGCUGUCUUGGAUCAGGAUCUUUGCAUGGAUCCCAGAACUUGAAGCGGGUGUCCGAUGACCUGCGCUUCCGGGAGUAAAGGUACCUCUGGCACACAGGCCAGUUCCUGCAGCUAUAGGAGAUGACCAUAAGGUAGAGCAGCUUGACAAGAUGGUUGACAGAAAAGGCAGGAUUUAAGAGCUUUCAUCAUCUUACAGGCAGACAUAUACACGAAAGUGGAUUGAAGUCUGUCUGUGCUGGCUAGCUUGGGGGCAUCAGUGCACAAGAUUUGCACCGACAUACGCCCUGGCAUCCAAGGGAGAUGGAGGAACCCUUUGAAACAGAUUGGCUCAAGUGCGAGUGCCAGCGGAAUCCAUGCGUUCAGAACGUUGCUGCAGUCUUGCCCGCCACCGGCAGGACCCUUGCAUGGACCCAUAUUGCGGAUGGCAUCUGUCCAGUGGUUUGAACGCCACUGGAUGAUAAUAGUGCCAUCGACAGGAUCUGUUUGGCCGAGGCAUUCUUACCGCAGAUACUGAAUACGCUGCAGAACAUUUGAAGGAUUGGUCGUGUCCCCAAGUAAUUGAACGGCGCUUCGGCAAGAGCUGCCUUUCAUGGCCACACAGAGAACAUCAUUUGGCCAAGCACAAAGCUGGAGGUAGCCGCCAGGAUUGCCAUAGGAAACCAGAGUGCUUCUCGGCAGGCAGCUUCUUUGUGGUUAAGCAGGGAAGGGGUGACAAUGACCUUCAUAGAGCGUAUCCAGGUUGAUGCCUUUCUUCAGUCCCAUUUACUCCCAGUUGGAUUAUACUGGAUCCUCUUUUCAAGUCGUGCCUCCCAGCAGGUGCAGAGAUUCUUUAGAAGAGGAGGUGUAUCCCUGUUAAACCAUAUGAAAGCGUGAUGAAGGUGAAAGCAGAAACACGUUUGUAAGAGUUGGAAGAGAAUUAAACGAAAAUCAUUGUU
+
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@B@@@@@@B@@@@@@@@@@@@@@@@@@@@@@@@AKD@@@@@@@@@@@@@@@@@@@

Offset=64
java.lang.Exception: Aborting.
        at shared.KillSwitch.kill(KillSwitch.java:108)
        at stream.FASTQ.quadToRead_slow(FASTQ.java:754)
        at stream.FASTQ.toReadList(FASTQ.java:625)
        at stream.FastqReadInputStream.fillBuffer(FastqReadInputStream.java:107)
        at stream.FastqReadInputStream.nextList(FastqReadInputStream.java:93)
        at stream.ConcurrentGenericReadInputStream$ReadThread.readLists(ConcurrentGenericReadInputStream.java:680)
        at stream.ConcurrentGenericReadInputStream$ReadThread.run(ConcurrentGenericReadInputStream.java:656)


################################################################################
################################################################################
TOTAL RUNNING TIME: 0 day(s), 0 hour(s), 0 minute(s), and 23 second(s)
################################################################################
################################################################################

```

**Comment by ndaniel** [comment]
Hi,

would be possible to get the exact command line that produces this error?

Running `tail -100 fusioncatcher.log` should show that!

Daniel
