### ISSUE TITLE
synonyms.txt

### ISSUE THREAD

**Issue by readmanchiu** [ndaniel/fusioncatcher#186]
Hello,

I installed fusioncatcher using bionconda and was trying to run `generate_banned.py` and got the following error:
```
Generating the list of banned fusion genes...
Traceback (most recent call last):
  File "/home/rchiu/anaconda2/envs/fusions/bin/generate_banned.py", line 12806, in <module>
    loci = symbols.generate_loci(file_symbols)
  File "/home/rchiu/anaconda2/envs/fusions/bin/symbols.py", line 750, in generate_loci
    genes = [line.rstrip('\r\n').split('\t') for line in file(gene_symbols_filename,'r').readlines()]
IOError: [Errno 2] No such file or directory: './synonyms.txt'
```
Where can I find `synonyms.txt`?

Thanks
Readman

**Comment by readmanchiu** [comment]
Figured out how to generate the file
