### ISSUE TITLE
Error message shared.KillSwitch.kill

### ISSUE THREAD

**Issue by Coaxecva** [ndaniel/fusioncatcher#191]
Hi Daniel,

I got this error message for some samples:

```
Memory: max=211237m, total=211237m, free=207740m, used=3497m

Input is being processed as paired
Started output streams: 0.070 seconds.
Warning! Changed from ASCII-33 to ASCII-64 on input ;: 59 -> 28
Up to 277350 prior reads may have been generated with incorrect qualities.
If this is a problem you may wish to re-run with the flag 'qin=33' or 'qin=64'.

The ASCII quality encoding offset (64) is not set correctly, or the reads are corrupt; quality value below -5.
Please re-run with the flag 'qin=33', 'ignorebadquality', or '-da'.
Problematic read number 277351:

@HWI-ST173R:607:D1C5FACXX:8:1106:4415:59068/1
GCCCAGAGAGGTTCACTCCCCATCCTGTACCAGTTTCATCATGAGGATGCTGCCCTGGAGCGTAGGTCGGCCAACTCTGCAGGGCAGCATCCTCATGATG
+
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@CCHBDCC@@@CCCDDC@@@@@BDDDCCAC@@C@@@

Offset=64
java.lang.Exception: Aborting.
        at shared.KillSwitch.kill(KillSwitch.java:108)
        at stream.FASTQ.quadToRead_slow(FASTQ.java:754)
        at stream.FASTQ.toReadList(FASTQ.java:625)
        at stream.FastqReadInputStream.fillBuffer(FastqReadInputStream.java:107)
        at stream.FastqReadInputStream.nextList(FastqReadInputStream.java:93)
        at stream.ConcurrentGenericReadInputStream$ReadThread.readLists(ConcurrentGenericReadInputStream.java:680)
        at stream.ConcurrentGenericReadInputStream$ReadThread.run(ConcurrentGenericReadInputStream.java:656)

```
Wonder if you can see what caused the error?

Thanks,
Coax

**Comment by Coaxecva** [comment]
Hi @ndaniel 

Please find the fastq files:
https://www.dropbox.com/s/zgse1sny96yixug/my_read_R1.fastq.gz?dl=0
https://www.dropbox.com/s/dfn0syuyibrsym9/my_read_R2.fastq.gz?dl=0

Coax
