### ISSUE TITLE
OverflowError: size does not fit in an int

### ISSUE THREAD

**Issue by ndaniel** [ndaniel/fusioncatcher#29]
I am running the latest version of FusionCatcher (that is v0.99.7a) and was able to install the tool successfully. For the human genome I was downloading the annotation files, however for the mouse genome I issues the the following command which raises an error message:

```
~/fusioncatcher/bin/fusioncatcher-build -g mus_musculus -o fusioncatcher/data/mus_musculus

...

get_genome.py \
--organism mus_musculus \
--server ftp.ensembl.org \
--output /home/gerlacda/fusioncatcher/data/mus_musculus/
--------------------------------------------------------------------------------
+-->EXECUTING...
Downloading the genome of organism 'mus_musculus' from Ensembl!
230 Anonymous access granted, restrictions apply
Downloading: /pub/current_fasta//mus_musculus/dna/Mus_musculus.GRCm38.dna.chromosome.MT.fa.gz
Downloading: /pub/current_fasta//mus_musculus/dna/Mus_musculus.GRCm38.dna.toplevel.fa.gz
Traceback (most recent call last):
  File "/home/gerlacda/fusioncatcher/bin/get_genome.py", line 161, in <module>
    file_content = f.read()
  File "/apps/prod/easybuild.el7.x86_64/software/Python/2.7.9-foss-2015a/lib/python2.7/gzip.py", line 261, in read
    self._read(readsize)
  File "/apps/prod/easybuild.el7.x86_64/software/Python/2.7.9-foss-2015a/lib/python2.7/gzip.py", line 320, in _read
    self._add_read_data( uncompress )
  File "/apps/prod/easybuild.el7.x86_64/software/Python/2.7.9-foss-2015a/lib/python2.7/gzip.py", line 336, in _add_read_data
    self.crc = zlib.crc32(data, self.crc) & 0xffffffffL
OverflowError: size does not fit in an int


ERROR: Workflow execution failed at step 4 while executing:
----------------
   get_genome.py \
   --organism mus_musculus \
   --server ftp.ensembl.org \
   --output /home/gerlacda/fusioncatcher/data/mus_musculus/
```
I found this python bug fix https://bugs.python.org/issue23306, but was wondering if there would be any other way to fix this, instead of rebuilding a completely new version of python.I am currently running python 2.7.9 on RedHat 7.3 with the kernel 3.10.0-327.13.1.

**Comment by ndaniel** [comment]
I was able to reproduce this bug! This has been fixed in FusionCatcher v0.99.7b.
