### ISSUE TITLE
bug in merge-reads.py for long reads

### ISSUE THREAD

**Issue by ndaniel** [ndaniel/fusioncatcher#57]
When the reads are longer than 130 bp the `merge-reads.py` fails in some cases with this error message:
```
////////////////////////////////////////////////////////////////////////////////
  Running: step = 103   Time: 10:26   Date: 2017-06-28 (elapsed time: 0d:0h:1m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher_results'
merge-reads.py \
-1 /projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher_results/A73845/fusions/original.fq \
-m /projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher_results/A73845/fusions/merged.fq \
-f /projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher_results/A73845/fusions/or1.fq \
-r /projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher_results/A73845/fusions/or2.fq \
-p 1
--------------------------------------------------------------------------------
+-->EXECUTING...
Traceback (most recent call last):
  File "/projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher/fusioncatcher/bin/merge-reads.py", line 689, in <module>
    verbose = False # verbose
  File "/projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher/fusioncatcher/bin/merge-reads.py", line 440, in merge_reads
    chunksize = 100
  File "/home/chmay/bin/lib/python2.7/multiprocessing/pool.py", line 287, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/chmay/bin/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
IndexError: string index out of range


ERROR: Workflow execution failed at step 103 while executing:
----------------
   merge-reads.py \
   -1 /projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher_results/A73845/fusions/original.fq \
   -m /projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher_results/A73845/fusions/merged.fq \
   -f /projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher_results/A73845/fusions/or1.fq \
   -r /projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher_results/A73845/fusions/or2.fq \
   -p 1
----------------
  * Size '/projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher_results/A73845/fusions/original.fq' = 24134084 bytes
  * Size '/projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher_results/A73845/fusions/merged.fq' = 1897209 bytes
  * Size '/projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher_results/A73845/fusions/or1.fq' = 344023 bytes
  * Size '/projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher_results/A73845/fusions/or2.fq' = 446435 bytes
  * Size '1' = 0 bytes


Executing second time the same step/command in order to capture error messages (i.e. STDERR)...

-------------------------------------------
Traceback (most recent call last):
  File "/projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher/fusioncatcher/bin/merge-reads.py", line 689, in <module>
    verbose = False # verbose
  File "/projects/clingenetics/cmay_dev/CLINGEN-4533_Analyze_IX5291_IDT_Illumina_TC/Fusioncatcher/fusioncatcher/bin/merge-reads.py", line 440, in merge_reads
    chunksize = 100
  File "/home/chmay/bin/lib/python2.7/multiprocessing/pool.py", line 287, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/chmay/bin/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
IndexError: string index out of range
```

**Comment by ndaniel** [comment]
Fixed today with a re-re-release of v0.99.7c.
