### ISSUE TITLE
fusioncatcher crashes at step 326 for large RNA-seq experiments

### ISSUE THREAD

**Issue by messersc** [ndaniel/fusioncatcher#69]
Hi,

I am running into kind of a strange bug. I have a collection of ~ 30 RNA-seq experiments from tumor samples, and due to a change in sequencing depth the last ones contain much more data than earlier batches.

Using the same code, I get segfaults for 5 samples at step 326, while the others work fine. I cannot really say what happens - I have tried giving the process much more memory, but that did not solve the issue.

One of the things I noticed is that the `exon-exon_junction_cut.fa` files for the samples that crash are bigger than 1 GB.

Here is the fusioncatcher.log, I removed the full paths.

```
////////////////////////////////////////////////////////////////////////////////
  Running: step = 326   Time: 15:42   Date: 2017-09-07 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: 'gene_fusion_calling_newfusioncatcher'
build_report_fusions_map.py \
--suporting_unique_reads 2 \
--anchor2 47 \
--input_exons biotools/fusioncatcher/fusioncatcher/data/current/exons.txt \
--input_candidate_fusion_genes out/candidate_fusion-genes_further.txt \
--input_fusion_summary out/candidate_fusion-genes_exon-exon-junctions_summary.txt \
--input_fusion_summary_more out/candidate_fusion-genes_exon-exon-junctions_reads-positions.txt \
--input_candidate_fusions_missing_mates out/candidate_fusion-genes_missing_mates.txt \
--input_fasta_juncs out/exon-exon_junction_cut.fa \
--tmp_dir /tmp/tmp.4ACvRfotpE/tmp.6RivFweYQh/ \
--input_fastq out/original_important.fq.gz \
--input_candidate_fusion_genes_reads out/candidate_fusion-genes_supporting_paired-reads.txt \
--output_super_summary out/candidate_fusion_genes_summary_BOWTIE.txt \
--output_zip_fasta out/supporting-reads_gene-fusions_BOWTIE.zip
--------------------------------------------------------------------------------
+-->EXECUTING...
```

Does anyone have an idea what might be happening? I am running fusioncatcher.py 0.99.7c beta.

edit:

I guess I cannot rule out memory problems yet. I'll keep you posted.

```
Executing second time the same step/command in order to capture error messages (i.e. STDERR)...

-------------------------------------------
Reading known exons... /fast/groups/cubi/projects/biotools/fusioncatcher/fusioncatcher/data/current/exons.txt
Reading... out/candidate_fusion-genes_exon-exon-junctions_summary.txt
Reading... out/exon-exon_junction_cut.fa
Reading... out/candidate_fusion-genes_exon-exon-junctions_reads-positions.txt
Reading... out/candidate_fusion-genes_further.txt
Reading... out/candidate_fusion-genes_supporting_paired-reads.txt
Reading... out/candidate_fusion-genes_missing_mates.txt
Traceback (most recent call last):
  File "/fast/groups/cubi/projects/biotools/fusioncatcher/fusioncatcher/bin/build_report_fusions_map.py", line 676, in <module>
    missing = [line.rstrip('\r\n').split('\t') for line in file(options.input_candidate_fusions_missing_mates_filename,'r').readlines()]
MemoryError
```

**Comment by ndaniel** [comment]
How many lines the file "out/candidate_fusion-genes_missing_mates.txt" has?

```
wc -l out/candidate_fusion-genes_missing_mates.txt
```

**Comment by messersc** [comment]
Hello Daniel,

the newest version that you linked above does not solve the issue for me:

```
  * Size '/fast/groups/cubi/projects/biotools/fusioncatcher/fusioncatcher/data/current/exons.txt' = 144615300 bytes
  * Size '/fast/groups/cubi/projects/2016-09-27_DKTK/pipeline/gene_fusion_calling_newfusioncatcher/work/fusioncatcher.D5i7k8/out/candidate_fusion-genes_further.txt' = 20939322 bytes
  * Size '/fast/groups/cubi/projects/2016-09-27_DKTK/pipeline/gene_fusion_calling_newfusioncatcher/work/fusioncatcher.D5i7k8/out/candidate_fusion-genes_exon-exon-junctions_summary.txt' = 103283 bytes
  * Size '/fast/groups/cubi/projects/2016-09-27_DKTK/pipeline/gene_fusion_calling_newfusioncatcher/work/fusioncatcher.D5i7k8/out/candidate_fusion-genes_exon-exon-junctions_reads-positions.txt' = 575945 bytes
  * Size '/fast/groups/cubi/projects/2016-09-27_DKTK/pipeline/gene_fusion_calling_newfusioncatcher/work/fusioncatcher.D5i7k8/out/candidate_fusion-genes_missing_mates.txt' = 2816358588 bytes
  * Size '/fast/groups/cubi/projects/2016-09-27_DKTK/pipeline/gene_fusion_calling_newfusioncatcher/work/fusioncatcher.D5i7k8/out/exon-exon_junction_cut.fa' = 4243356983 bytes
  * Size '/fast/groups/cubi/projects/2016-09-27_DKTK/pipeline/gene_fusion_calling_newfusioncatcher/work/fusioncatcher.D5i7k8/out/original_important.fq.gz' = 5809325540 bytes
  * Size '/fast/groups/cubi/projects/2016-09-27_DKTK/pipeline/gene_fusion_calling_newfusioncatcher/work/fusioncatcher.D5i7k8/out/candidate_fusion-genes_supporting_paired-reads.txt' = 30106321 bytes
  * Size '/fast/groups/cubi/projects/2016-09-27_DKTK/pipeline/gene_fusion_calling_newfusioncatcher/work/fusioncatcher.D5i7k8/out/candidate_fusion_genes_summary_BOWTIE.txt' = 62152 bytes
  * Size '/fast/groups/cubi/projects/2016-09-27_DKTK/pipeline/gene_fusion_calling_newfusioncatcher/work/fusioncatcher.D5i7k8/out/supporting-reads_gene-fusions_BOWTIE.zip' = 0 bytes         


Executing second time the same step/command in order to capture error messages (i.e. STDERR)...

-------------------------------------------
Traceback (most recent call last):
  File "/fast/groups/cubi/projects/biotools/fusioncatcher/fusioncatcher/bin/build_report_fusions_map.py", line 676, in <module>
    missing = [line.rstrip('\r\n').split('\t') for line in file(options.input_candidate_fusions_missing_mates_filename,'r') if line.find(",")==-1]
MemoryError


################################################################################
################################################################################
TOTAL RUNNING TIME: 0 day(s), 0 hour(s), 15 minute(s), and 41 second(s)
################################################################################
################################################################################
```

Here are the output of `wc -l` on each of the `candidate_fusion-genes_missing_mates.txt` files, with the last 6 breaking:

```
1366028 ./fusioncatcher.Dtx5ig/out/candidate_fusion-genes_missing_mates.txt
1394995 ./fusioncatcher.D8h89j/out/candidate_fusion-genes_missing_mates.txt
1441709 ./fusioncatcher.D3b8kq/out/candidate_fusion-genes_missing_mates.txt
1623915 ./fusioncatcher.Dzpf4m/out/candidate_fusion-genes_missing_mates.txt
1951901 ./fusioncatcher.Drmw2x/out/candidate_fusion-genes_missing_mates.txt
2350654 ./fusioncatcher.Doo7xo/out/candidate_fusion-genes_missing_mates.txt
2351833 ./fusioncatcher.D9fha4/out/candidate_fusion-genes_missing_mates.txt
2457644 ./fusioncatcher.Dzsleo/out/candidate_fusion-genes_missing_mates.txt
2609993 ./fusioncatcher.Dftmp3/out/candidate_fusion-genes_missing_mates.txt
3960431 ./fusioncatcher.D1wl9k/out/candidate_fusion-genes_missing_mates.txt
4113126 ./fusioncatcher.D2swcy/out/candidate_fusion-genes_missing_mates.txt
4153219 ./fusioncatcher.Dp1pyq/out/candidate_fusion-genes_missing_mates.txt
4170406 ./fusioncatcher.Dw9t0v/out/candidate_fusion-genes_missing_mates.txt
4284293 ./fusioncatcher.Dfdejz/out/candidate_fusion-genes_missing_mates.txt
4315489 ./fusioncatcher.Dgyi13/out/candidate_fusion-genes_missing_mates.txt
4509835 ./fusioncatcher.Db7nlh/out/candidate_fusion-genes_missing_mates.txt
4682190 ./fusioncatcher.Djjzwz/out/candidate_fusion-genes_missing_mates.txt
4773405 ./fusioncatcher.Dnlod5/out/candidate_fusion-genes_missing_mates.txt
4854467 ./fusioncatcher.Dolnm7/out/candidate_fusion-genes_missing_mates.txt
5038695 ./fusioncatcher.Dnxxr0/out/candidate_fusion-genes_missing_mates.txt
6457413 ./fusioncatcher.Ddctr6/out/candidate_fusion-genes_missing_mates.txt
58221888 ./fusioncatcher.Daupgf/out/candidate_fusion-genes_missing_mates.txt
69974724 ./fusioncatcher.D5i7k8/out/candidate_fusion-genes_missing_mates.txt
74170953 ./fusioncatcher.Do3ct1/out/candidate_fusion-genes_missing_mates.txt
83434071 ./fusioncatcher.Dk9cwx-2/out/candidate_fusion-genes_missing_mates.txt
83757811 ./fusioncatcher.D9yibv/out/candidate_fusion-genes_missing_mates.txt
140145702 ./fusioncatcher.D5eqt4/out/candidate_fusion-genes_missing_mates.txt
```

**Comment by ndaniel** [comment]
Ok. Thanks for the extra info!

Shortly, it looks like those files are too big for Python's standard list/dictionary (for example a list of 140 million of elements). Adding extra memory will not help here (if there is already at least available 32GB free RAM). Therefore that Python lines need to be re-written in something what Python can handle.

How many input reads have those last 6 samples which fail?

**Comment by ndaniel** [comment]
@messersc 

I did some more changes to https://github.com/ndaniel/fusioncatcher/blob/master/bin/build_report_fusions_map.py . Does this help?

**Comment by messersc** [comment]
Hi Daniel,

thanks for looking into this so quickly! I will try your patch and also look up the numbers you wanted in your last post. Right now, I am doing some more testing, because I am still not sure if this is a bug in fusioncatcher or our pipeline/cluster set up.

Clemens

**Comment by ndaniel** [comment]
any new info?
